In [1]:
#Question 1
x= 'Parvathy'
print(x[::2])
print(x[1::2])


Prah
avty


In [42]:
#Question 2
Student_name=('Parvathy', 'Deepa')
Course_name=('Data Science', 'Data Analytics')
Email_address=('p@gmail.com', 'd@gmail.com')

stu_name=Student_name+("Angel", "Ritu", "Govind", "Peter", "Andy")
crs_name=Course_name+("IT", "Maths", "Political Science", "Statistics", "Computer Science")
em_address=Email_address+("i@gmail.com", "r@gmail.com", "m@gmail.com","p@gmail.com", "a@gmail.com")
print(stu_name)
print(crs_name)
print(em_address)

('Parvathy', 'Deepa', 'Angel', 'Ritu', 'Govind', 'Peter', 'Andy')
('Data Science', 'Data Analytics', 'IT', 'Maths', 'Political Science', 'Statistics', 'Computer Science')
('p@gmail.com', 'd@gmail.com', 'i@gmail.com', 'r@gmail.com', 'm@gmail.com', 'p@gmail.com', 'a@gmail.com')


In [12]:
#Question 3
y={
    Student_name:('Parvathy', 'Deepa'),
    Course_name: ('Data Science', 'Data Analytics')
    }
print (y)

{('Parvathy', 'Deepa'): ('Parvathy', 'Deepa'), ('Data Science', 'Data Analytics'): ('Data Science', 'Data Analytics')}


In [2]:
#Question 4

energy= 'Fossil'
if(energy=='Fossil'):
    print("Natural Gas")
elif(energy=='Renewable'):
    print("Solar Power")
else:
    print("Not in the list")


Natural Gas


In [41]:
#Question 5

#for loop to take values from 0 to 100
for x in range(0,101):
    count=0
    #for loop to check the modulus
    for y in range(1,x):
        if((x+1)%y==0):
            #prime numbers are divisible only by 1 and itself
            count+=1
    #checking if number is prime
    if(count<2):
        print(x+1)
        print("\n")

1


2


3


5


7


11


13


17


19


23


29


31


37


41


43


47


53


59


61


67


71


73


79


83


89


97


101




In [32]:
#Question 6

# Example of breaking a loop before executing for the defined number of iterations
count = 0
while count < 10:
    if count == 5:
        break  # Break out of the loop when count reaches 5
    print("Count:", count)
    count += 1


Count: 0
Count: 1
Count: 2
Count: 3
Count: 4


In [33]:
#Question 7

#defining function for addition
def Addition(x, y):
    return x + y

#defining function for addition
def Multiplication(x, y):
    return x * y

#defining function for addition
def Division(x, y):
    return x / y

#defining function for addition
def Subtraction(x, y):
    return x - y

# Calling the functions with arguments (4, 7) and printing the outputs
x = 4
y = 7

print("Addition:", Addition(x, y))
print("Multiplication:", Multiplication(x, y))
print("Division:", Division(x, y))
print("Subtraction:", Subtraction(x, y))


Addition: 11
Multiplication: 28
Division: 0.5714285714285714
Subtraction: -3


In [34]:
#Question 8
import numpy as np

# Create an 8x8 identity matrix
identity_matrix = np.eye(8)

# Display the identity matrix
print("Identity Matrix:")
print(identity_matrix)

# Create an 8x4 random matrix
random_matrix = np.random.rand(8, 4)

# Display the random matrix
print("\nRandom Matrix:")
print(random_matrix)

# Multiply the identity matrix with the random matrix
result_matrix = np.dot(identity_matrix, random_matrix)

# Display the result of the multiplication
print("\nResult Matrix:")
print(result_matrix)


Identity Matrix:
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]

Random Matrix:
[[0.73500042 0.67205693 0.87555034 0.20597216]
 [0.13024456 0.52319221 0.54934925 0.81089858]
 [0.66127934 0.6639486  0.37180826 0.36626568]
 [0.86490292 0.44588984 0.86242709 0.67062073]
 [0.84137971 0.97645931 0.71849909 0.70590668]
 [0.55453278 0.00732308 0.4176255  0.80315366]
 [0.94255052 0.81368288 0.7914093  0.4740902 ]
 [0.35342727 0.06851418 0.13505547 0.32744751]]

Result Matrix:
[[0.73500042 0.67205693 0.87555034 0.20597216]
 [0.13024456 0.52319221 0.54934925 0.81089858]
 [0.66127934 0.6639486  0.37180826 0.36626568]
 [0.86490292 0.44588984 0.86242709 0.67062073]
 [0.84137971 0.97645931 0.71849909 0.70590668]
 [0.55453278 0.00732308 0.4176255  0.80315366]
 [0.94255052 0.81368288 0.7914093  0.4740902 ]
 [0.35342727 0.06851418 0.13

In [36]:
#Question 9
import numpy as np

# Create an 8x9 matrix with random values
matrix = np.random.rand(8, 9)

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Transpose the matrix
transposed_matrix = np.transpose(matrix)

# Print the transposed matrix
print("\nTransposed Matrix:")
print(transposed_matrix)

# Check the shape of the original and transposed matrices
print("\nShape of Original Matrix:", matrix.shape)
print("Shape of Transposed Matrix:", transposed_matrix.shape)


Original Matrix:
[[0.5759251  0.81508354 0.0101097  0.9676248  0.74092034 0.30527806
  0.84244353 0.12887124 0.97886293]
 [0.5587343  0.67533216 0.58006872 0.53983538 0.54111431 0.22218437
  0.38440509 0.73459395 0.95306516]
 [0.23344036 0.54148304 0.63774432 0.80333903 0.34605754 0.27956965
  0.6259601  0.40438193 0.06374546]
 [0.87714003 0.91093568 0.29602653 0.62227292 0.96384079 0.00934243
  0.60686181 0.73048523 0.66691199]
 [0.51475103 0.72041696 0.89952663 0.82983729 0.34745061 0.04570765
  0.82205782 0.40484969 0.60201927]
 [0.88291087 0.99093307 0.30325127 0.55243628 0.96358251 0.65292141
  0.27724961 0.60405662 0.37612702]
 [0.87501434 0.46551308 0.40643362 0.26473443 0.39477795 0.26654628
  0.03706632 0.97639484 0.7318225 ]
 [0.21552486 0.82766442 0.60093052 0.17580114 0.58010073 0.09232124
  0.44198203 0.59276184 0.69746407]]

Transposed Matrix:
[[0.5759251  0.5587343  0.23344036 0.87714003 0.51475103 0.88291087
  0.87501434 0.21552486]
 [0.81508354 0.67533216 0.54148304 0.

In [40]:
#Question 10
import pandas as pd
import csv

# Load the dataset
data = pd.read_csv("pedestrian-counting.csv")

# Display the number of data instances and variables
num_instances, num_variables = data.shape
print("Number of data instances:", num_instances)
print("Number of variables:", num_variables)

# Extract the third variable
third_variable = data.iloc[:, 2]

# Calculate the mean of the third variable
mean_third_variable = third_variable.mean()

# Deduct the mean from the original values
modified_third_variable = third_variable - mean_third_variable

# Print both original and modified values of the variable
print("\nOriginal values of the third variable:")
print(third_variable)
print("\nModified values of the third variable (mean deducted):")
print(modified_third_variable)


Number of data instances: 525005
Number of variables: 7

Original values of the third variable:
0          75
1          75
2          75
3          75
4          75
         ... 
525000    142
525001    142
525002    142
525003    142
525004    142
Name: LocationID, Length: 525005, dtype: int64

Modified values of the third variable (mean deducted):
0         21.822695
1         21.822695
2         21.822695
3         21.822695
4         21.822695
            ...    
525000    88.822695
525001    88.822695
525002    88.822695
525003    88.822695
525004    88.822695
Name: LocationID, Length: 525005, dtype: float64
